# Generated by Django 4.2.11 on 2025-08-26 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmoi',
            name='date_publication',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
