# Generated by Django 4.2.11 on 2025-08-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0002_contactmoi_date_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmoi',
            old_name='dest_name',
            new_name='Full_name',
        ),
        migrations.AddField(
            model_name='contactmoi',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
