# Generated by Django 4.2.11 on 2025-08-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0003_rename_dest_name_contactmoi_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
