# Generated by Django 4.2.11 on 2025-08-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0004_alter_portfolio_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
