# Generated by Django 4.2.11 on 2025-09-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0005_alter_projet_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='balise',
            field=models.CharField(default='HTML', max_length=100),
        ),
        migrations.AddField(
            model_name='projet',
            name='base_donnee',
            field=models.CharField(default='Mysql', max_length=100),
        ),
        migrations.AddField(
            model_name='projet',
            name='en_pluse',
            field=models.CharField(default='API', max_length=100),
        ),
        migrations.AddField(
            model_name='projet',
            name='language',
            field=models.CharField(default='Python', max_length=100),
        ),
        migrations.AddField(
            model_name='projet',
            name='script',
            field=models.CharField(default='JavaScript', max_length=100),
        ),
        migrations.AddField(
            model_name='projet',
            name='style',
            field=models.CharField(default='CSS', max_length=100),
        ),
    ]
